name: Schedule QA Automation Trigger

on:
  push:
    branches:
      - dev-deploy  # Change this to the branch where you merge code

jobs:
  schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Wait for 10 seconds
        run: sleep 10

      - name: Create a repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: SkyTradeLinks/qa-automation
          event-type: trigger-automation
          token: ${{ secrets.PRIVATE_KEY_QA }}# Use custom token